[terminal]
shell = { program = "/opt/homebrew/bin/tmux", args = [
  "new-session",
  "-A",
  "-s",
  "main",
] }

[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[window]
decorations = "buttonless"
opacity = 0.35
blur = true
option_as_alt = "Both"
dynamic_padding = true
padding = { x = 10, y = 8 }

[font]
size = 13
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[colors]
primary = { background = "#000000" }
cursor = { text = "CellBackground", cursor = "#CDC0AD" }

[mouse]
hide_when_typing = true
